# Generated by Django 5.2.11 on 2026-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_deadlineextensionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="DeadlineExtensionRequest",
        ),
    ]
