# Generated by Django 5.2.11 on 2026-08-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_deadlineextensionrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeadlineExtensionRequest",
        ),
    ]
