# Generated by Django 5.2.11 on 2026-10-09 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_priority_delete_deadlineextensionrequest"),
        (
            "users",
            "0003_teamtransferrequest_unique_pending_transfer_per_member_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["available", "assigned", "taken", "completed"])
                ),
                name="subtask_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "progress__in",
                        [
                            "not_started",
                            "assigned",
                            "in_progress",
                            "testing",
                            "completed",
                        ],
                    )
                ),
                name="subtask_valid_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ["low", "medium", "high"])),
                name="subtask_valid_priority",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "completed", "archived"])),
                name="task_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ["low", "medium", "high"])),
                name="task_valid_priority",
            ),
        ),
    ]
