# Generated by Django 5.2.11 on 2026-10-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teamtransferrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teamtransferrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING_CURRENT", "PENDING_FUTURE"])
                ),
                fields=("member",),
                name="unique_pending_transfer_per_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamtransferrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_team", models.F("future_team")), _negated=True
                ),
                name="transfer_different_teams",
            ),
        ),
    ]
