# Generated by Django 5.2.11 on 2026-10-09 10:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "users",
            "0003_teamtransferrequest_unique_pending_transfer_per_member_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_case_insensitive_unique",
            ),
        ),
    ]
